Cfm.Web.Mvc/Areas/Admin/Controllers/FunctionController.cs
using Cfm.Web.Mvc.Areas.Admin.Models;
using Cfm.Web.Mvc.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cfm.Web.Mvc.Areas.Admin.Controllers
{
    [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.Center, (int)Constant.POLevel.Branch })]
    public class FunctionController : BaseController
    {
        // GET: Admin/Function
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]

        public ActionResult Function(int Type)
        {
            ViewBag.Type = Type;
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfigCenter()
        {
            return PartialView();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult UnitCenter()
        {
            return PartialView();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ParameterService(int PageIndex = 0)
        {
            List<ReportListViewModel> listReport = new List<ReportListViewModel>();
            var rs = Helper.Invoke("GET", string.Format("api/Dictionary/GetReportList?id={0}&PageIndex = {1}&PageSize ={2}", new object[] { 0, 0, Constant.PageSize }), null);
            if (rs != null && rs.ListValue != null)
            {

                foreach (dynamic dyn in rs.ListValue)
                {
                    var report = new ReportListViewModel()
                    {
                        Id = dyn.Id,
                        Code = dyn.Code,
                        Name = dyn.Name,
                        On_Moc = dyn.On_Moc,
                        On_Province_PO = dyn.On_Province_PO,
                        On_District_PO = dyn.On_District_PO,
                        On_PO = dyn.On_PO,
                        AllowCreateEntry = dyn.AllowCreateEntry,
                        OfficeManage = dyn.OfficeManage,
                        Description = dyn.Description,
                        ReportType = dyn.ReportType
                    };
                    if (!listReport.Contains(report))
                    {
                        listReport.Add(report);
                    }
                }
            }

            return PartialView(listReport);
        }


        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult FundBranch()
        {
            return PartialView();
        }
    }
}

Cfm.Web.Mvc/Areas/CFMBranch/Controllers/FunctionController.cs
using Cfm.Web.Mvc.Areas.Admin.Models;
using Cfm.Web.Mvc.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cfm.Web.Mvc.Areas.CFMBranch.Controllers
{
    public class FunctionController : Controller
    {
        // GET: CFMBranch/Function
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfigPO()
        {
            return View();
        }

        public ActionResult AccountingBranch()
        {
            List<ReportListViewModel> listReport = new List<ReportListViewModel>();
            var rs = Helper.Invoke("GET", string.Format("api/Dictionary/GetReportList?id={0}&PageIndex = {1}&PageSize ={2}", new object[] { 0, 0, Constant.PageSize }), null);
            if (rs != null && rs.ListValue != null)
            {

                foreach (dynamic dyn in rs.ListValue)
                {
                    var report = new ReportListViewModel()
                    {
                        Id = dyn.Id,
                        Code = dyn.Code,
                        Name = dyn.Name,
                        On_Moc = dyn.On_Moc,
                        On_Province_PO = dyn.On_Province_PO,
                        On_District_PO = dyn.On_District_PO,
                        On_PO = dyn.On_PO,
                        AllowCreateEntry = dyn.AllowCreateEntry,
                        OfficeManage = dyn.OfficeManage,
                        Description = dyn.Description,
                        ReportType = dyn.ReportType
                    };
                    if (!listReport.Contains(report))
                    {
                        listReport.Add(report);
                    }
                }
            }
            return PartialView(listReport);
        }

        public ActionResult StatisticGeneral()
        {
            List<ReportListViewModel> listReport = new List<ReportListViewModel>();
            var rs = Helper.Invoke("GET", string.Format("api/Dictionary/GetReportList?id={0}&PageIndex = {1}&PageSize ={2}", new object[] { 0, 0, Constant.PageSize }), null);
            if (rs != null && rs.ListValue != null)
            {

                foreach (dynamic dyn in rs.ListValue)
                {
                    var report = new ReportListViewModel()
                    {
                        Id = dyn.Id,
                        Code = dyn.Code,
                        Name = dyn.Name,
                        On_Moc = dyn.On_Moc,
                        On_Province_PO = dyn.On_Province_PO,
                        On_District_PO = dyn.On_District_PO,
                        On_PO = dyn.On_PO,
                        AllowCreateEntry = dyn.AllowCreateEntry,
                        OfficeManage = dyn.OfficeManage,
                        Description = dyn.Description,
                        ReportType = dyn.ReportType
                    };
                    if (!listReport.Contains(report))
                    {
                        listReport.Add(report);
                    }
                }
            }
            return PartialView(listReport);
        }

        public ActionResult BusinessSupport()
        {
            return PartialView();
        }
    }
}

Cfm.Web.Mvc/Areas/CFMCounter/Controllers/FunctionController.cs
using Cfm.Web.Mvc.Areas.Admin.Controllers;
using Cfm.Web.Mvc.Areas.Admin.Models;
using Cfm.Web.Mvc.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cfm.Web.Mvc.Areas.CFMCounter.Controllers
{
    [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.Counter })]
    public class FunctionController : BaseController
    {
        // GET: CFMCounter/Function
        public ActionResult Index()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]

        public ActionResult FunctionPO()
        {
            List<ReportListViewModel> listReport = new List<ReportListViewModel>();
            var rs = Helper.Invoke("GET", string.Format("api/Dictionary/GetReportList?id={0}&PageIndex = {1}&PageSize ={2}", new object[] { 0, 0, Constant.PageSize }), null);
            if (rs != null && rs.ListValue != null)
            {

                foreach (dynamic dyn in rs.ListValue)
                {
                    var report = new ReportListViewModel()
                    {
                        Id = dyn.Id,
                        Code = dyn.Code,
                        Name = dyn.Name,
                        On_Moc = dyn.On_Moc,
                        On_Province_PO = dyn.On_Province_PO,
                        On_District_PO = dyn.On_District_PO,
                        On_PO = dyn.On_PO,
                        AllowCreateEntry = dyn.AllowCreateEntry,
                        OfficeManage = dyn.OfficeManage,
                        Description = dyn.Description,
                        ReportType = dyn.ReportType
                    };
                    if (!listReport.Contains(report))
                    {
                        listReport.Add(report);
                    }
                }
            }
           
            return PartialView(listReport);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfigPO()
        {
            return PartialView();
        }
    }
}

Cfm.Web.Mvc/Areas/CFMDistrict/Controllers/FunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cfm.Web.Mvc.Areas.Admin.Models;
using Cfm.Web.Mvc.Common;
using Cfm.Web.Mvc.Areas.Admin.Controllers;

namespace Cfm.Web.Mvc.Areas.CFMDistrict.Controllers
{
     [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.District })]
    public class FunctionController : BaseController
    {
        // GET: CFMDistrict/Function
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ConfigDistrict()
        {
            return PartialView();
        }

        public ActionResult AccountingDistrict()
        {
            List<ReportListViewModel> listReport = new List<ReportListViewModel>();
            var rs = Helper.Invoke("GET", string.Format("api/Dictionary/GetReportList?id={0}&PageIndex = {1}&PageSize ={2}", new object[] { 0, 0, Constant.PageSize }), null);
            if (rs != null && rs.ListValue != null)
            {

                foreach (dynamic dyn in rs.ListValue)
                {
                    var report = new ReportListViewModel()
                    {
                        Id = dyn.Id,
                        Code = dyn.Code,
                        Name = dyn.Name,
                        On_Moc = dyn.On_Moc,
                        On_Province_PO = dyn.On_Province_PO,
                        On_District_PO = dyn.On_District_PO,
                        On_PO = dyn.On_PO,
                        AllowCreateEntry = dyn.AllowCreateEntry,
                        OfficeManage = dyn.OfficeManage,
                        Description = dyn.Description,
                        ReportType = dyn.ReportType
                    };
                    if (!listReport.Contains(report))
                    {
                        listReport.Add(report);
                    }
                }
            }
            return PartialView(listReport);
        }

        public ActionResult MoneyManageDistrict()
        {
            List<ReportListViewModel> listReport = new List<ReportListViewModel>();
            var rs = Helper.Invoke("GET", string.Format("api/Dictionary/GetReportList?id={0}&PageIndex = {1}&PageSize ={2}", new object[] { 0, 0, Constant.PageSize }), null);
            if (rs != null && rs.ListValue != null)
            {

                foreach (dynamic dyn in rs.ListValue)
                {
                    var report = new ReportListViewModel()
                    {
                        Id = dyn.Id,
                        Code = dyn.Code,
                        Name = dyn.Name,
                        On_Moc = dyn.On_Moc,
                        On_Province_PO = dyn.On_Province_PO,
                        On_District_PO = dyn.On_District_PO,
                        On_PO = dyn.On_PO,
                        AllowCreateEntry = dyn.AllowCreateEntry,
                        OfficeManage = dyn.OfficeManage,
                        Description = dyn.Description,
                        ReportType = dyn.ReportType
                    };
                    if (!listReport.Contains(report))
                    {
                        listReport.Add(report);
                    }
                }
            }
            return PartialView(listReport);
        }

        public ActionResult QualityDistrict()
        {
            return PartialView();
        }

        public ActionResult BusinessSupportDistrict()
        {
            return PartialView();
        }

        public ActionResult AccountingEntryDistrict()
        {
            return PartialView();
        }
    }
}

Cfm.Web.Mvc/Areas/Admin/Views/Function/ConfigCenter.cshtml
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    <li class="active">Hệ thống</li>
</ol>

<div class="row">
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("PoManage", "System", new { Area = "CFMCounter" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Quản lý Đơn vị
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("UserManage", "System", new { Area = "CFMCounter" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Quản lý Người dùng
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("RoleManage", "Home", new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Phân quyền Người dùng
                </div>
            </div>
        </a>
    </div>
</div>

Cfm.Web.Mvc/Areas/Admin/Views/Function/Function.cshtml
@using Cfm.Web.Mvc.Common;
@{
    var Type = int.Parse(ViewBag.Type.ToString());
}

@{
    if (Type == ((int)Constant.FunctionType.FundBranch))
    {
        Layout = "~/Areas/CFMBranch/Views/Shared/_Layout.cshtml";
    }
    else if (Type == ((int)Constant.FunctionType.ConfigCenter) || Type == ((int)Constant.FunctionType.UnitCenter) || Type == ((int)Constant.FunctionType.ReportCenter))
    {
        Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    }
}


@if (Type == ((int)Constant.FunctionType.ConfigCenter))
{
    Html.RenderAction("ConfigCenter", "Function", new { @Area = "Admin" });
}
else if (Type == ((int)Constant.FunctionType.UnitCenter))
{
    Html.RenderAction("UnitCenter", "Function", new { @Area = "Admin" });
}
else if (Type == ((int)Constant.FunctionType.ReportCenter))
{
    Html.RenderAction("ParameterService", "Function", new { @Area = "Admin" });
}
else if(Type == ((int)Constant.FunctionType.FundBranch))
{
    Html.RenderAction("FundBranch", "Function", new { @Area = "Admin" });
}

Cfm.Web.Mvc/Areas/Admin/Views/Function/FundBranch.cshtml
@{ Layout = null; }
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    <li class="active">Tiếp nộp quỹ</li>
</ol>
<div class="row">
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("AllocateFundManage","AccountingEntry",new { Area = "CFMDistrict"})">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Tiếp nộp quỹ
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("BorrowFundManage","AccountingEntry",new { Area = "CFMDistrict" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Vay trả quỹ khác
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("PayBankManage","AccountingEntry",new { Area = "CFMDistrict" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Rút nộp ngân hàng
                </div>
            </div>
        </a>
    </div>
    @*<div class="col-xs-3">
            <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("FeeForeignCurrency","AccountingEntry",new { Area = "CFMDistrict"})">
                <div class="tiles-body">
                    <div class="text-center">
                        <i class="fa fa-user fa-2x"></i>
                    </div>
                </div>
                <div class="tiles-footer">
                    <div class="pull-left percent-change">
                        Nhập lãi, phí ngoại tệ
                    </div>
                </div>
            </a>
        </div>*@
</div>
<hr class="Style1" />
<div class="row">
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("AllocateFundReplaceManage","AccountingEntry",new { Area = "CFMDistrict"})">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Nhập thay thế Tiếp nộp quỹ
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("BorrowFundReplaceManage","AccountingEntry",new { Area = "CFMDistrict"})">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Nhập thay thế Vay trả quỹ khác
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("PayBankReplaceManage","AccountingEntry",new { Area = "CFMDistrict"})">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Nhập thay thế Nộp ngân hàng
                </div>
            </div>
        </a>
    </div>

</div>

Cfm.Web.Mvc/Areas/Admin/Views/Function/ParameterService.cshtml
@model List<Cfm.Web.Mvc.Areas.Admin.Models.ReportListViewModel>
@{ Layout = null; }
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    <li class="active">Cấu hình báo cáo</li>
</ol>

<!--Danh mục-->
<div class="row">
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("Index","PostOffice",new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Bưu cục
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("ReportList","Dictionary",new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Danh mục báo cáo
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("ItemType","Dictionary",new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Loại chỉ tiêu
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("ItemGroup","Dictionary",new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Nhóm chỉ tiêu
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("ItemList","Dictionary",new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Danh mục chỉ tiêu
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("MappingManager","Mapping",new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Danh mục chỉ tiêu kết nối
                </div>
            </div>
        </a>
    </div>
    <div class="col-xs-3">
        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("TransferEntryManager","Mapping",new { Area = "Admin" })">
            <div class="tiles-body">
                <div class="text-center">
                    <i class="fa fa-user fa-2x"></i>
                </div>
            </div>
            <div class="tiles-footer">
                <div class="pull-left percent-change">
                    Bút toán kết chuyển
                </div>
            </div>
        </a>
    </div>
</div>
<!--End Danh mục-->
<hr class="Style1" />
<!--Cấu hình báo cáo-->
@if (Model != null && Model.Count > 0)
{
    <div class="row">
        @for (int i = 0; i < Model.Count; i++)
        {
            var item = Model[i];
            if (item.ReportType.EndsWith("CD") || item.ReportType.EndsWith("CD_DETAIL"))
            {
                if (!item.ReportType.StartsWith("04"))
                {
                    <div class="col-xs-3">
                        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("ConfigCD","ReportConfiguration",new { Area = "Admin", @reportID = @item.Id, @reportName = @item.Name })">
                            <div class="tiles-body">
                                <div class="text-center">
                                    <i class="fa fa-user fa-2x"></i>
                                </div>
                            </div>
                            <div class="tiles-footer">
                                <div class="pull-left percent-change">
                                    @item.Name
                                </div>
                            </div>
                        </a>
                    </div>
                }
                else
                {
                    <div class="col-xs-3">
                        <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("Config04CD","ReportConfiguration",new { Area = "Admin", @reportID = @item.Id, @reportName = @item.Name })">
                            <div class="tiles-body">
                                <div class="text-center">
                                    <i class="fa fa-user fa-2x"></i>
                                </div>
                            </div>
                            <div class="tiles-footer">
                                <div class="pull-left percent-change">
                                    @item.Name
                                </div>
                            </div>
                        </a>
                    </div>
                }

            }
            else if (item.ReportType == "03TH" || item.ReportType == "02TH" || item.ReportType == "01TH")
            {
                <div class="col-xs-3">
                    <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("ConfigReport", "ReportConfiguration", new { Area = "Admin", @ReportId = @item.Id, @ReportType = item.ReportType })">
                        <div class="tiles-body">
                            <div class="text-center">
                                <i class="fa fa-user fa-2x"></i>
                            </div>
                        </div>
                        <div class="tiles-footer">
                            <div class="pull-left percent-change">
                                @item.Name
                            </div>
                        </div>
                    </a>
                </div>
            }
            else if (item.ReportType.EndsWith("TQ"))
            {
                <div class="col-xs-3">
                    <a class="info-tiles tiles-cfm has-footer" href="@Url.Action("ConfigTQ","ReportConfiguration",new { Area = "Admin", @reportID = @item.Id, @reportName = @item.Name })">
                        <div class="tiles-body">
                            <div class="text-center">
                                <i class="fa fa-user fa-2x"></i>
                            </div>
                        </div>
                        <div class="tiles-footer">
                            <div class="pull-left percent-change">
                                @item.Name
                            </div>
                        </div>
                    </a>
                </div>
            }

        }
    </div>
    <!--End Cấu hình báo cáo-->
}

Cfm.Web.Mvc/Areas/Admin/Views/Function/UnitCenter.cshtml
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    <li class="active">Chức năng đơn vị Đầu mối</li>
</ol>

<div class="row">
    @for (int i = 0; i < 12; i++)
    {
        var stt = i + 1;
        <div class="col-xs-3">
            <a class="info-tiles tiles-cfm has-footer" href="javascript:void(0)">
                <div class="tiles-body">
                    <div class="text-center">
                        <i class="fa fa-user fa-2x"></i>
                    </div>
                </div>
                <div class="tiles-footer">
                    <div class="pull-left percent-change">
                        @(stt.ToString() + ". Quản lý người dùng")
                    </div>
                </div>
            </a>
        </div>
    }
</div>