Cfm.Web.Mvc/Areas/CFMBranch/Controllers/AccountingController.cs
using Cfm.Web.Mvc.Areas.Admin.Controllers;
using Cfm.Web.Mvc.Areas.Admin.Models;
using Cfm.Web.Mvc.Areas.CFMBranch.Models;
using Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel;
using Cfm.Web.Mvc.Areas.CFMDistrict.Models.ViewModels;
using Cfm.Web.Mvc.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cfm.Web.Mvc.Areas.CFMBranch.Controllers
{
    [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.Branch })]
    public class AccountingController : BaseController
    {
        // GET: CFMBranch/Accounting
        public ActionResult Index()
        {
            return View();
        }

        #region Report 02CD
        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Report02CD(int reportID = 0, string reportDate = "")
        {
            List<ItemGroupViewModel> listItemGroup = new List<ItemGroupViewModel>();
            List<int> ListItemGroupID = new List<int>();
            List<int> ListItemGroupID_TDV = new List<int>();
            List<int> ListItemGroupID_TKBD = new List<int>();
            List<int> ListItemGroupID_KD = new List<int>();

            CD02HeaderViewModel CD02Header = new CD02HeaderViewModel();
            CD02Header.ListDetail = new List<CD02DetailViewModel>();
            EmployeeViewModel oEmployee = (EmployeeViewModel)Session[Constant.EMP_SESSION];
            CD02Header.PoId = oEmployee.POID;
            CD02Header.ApprovedEmpId = oEmployee.ID;
            int Total = 0;
            CD02Header.ReportDate = DateTime.Now.ToString("dd/MM/yyyy");
            string Url = string.Format("api/Dictionary/ItemGroupGet/{0}?Code={1}&Name={2}&Status={3}&ReportId={6}&PageIndex={4}&PageSize={5}", 0, "", "", "", 0, Constant.PageSize, reportID);
            var rs = Helper.Invoke(Constant.Method.GET.ToString(), Url, null);

            if (rs.Code == "00")
            {
                int.TryParse(rs.Value.ToString(), out Total);
                dynamic oValue = rs.ListValue;
                foreach (var item in oValue)
                {
                    if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.Center)
                        ListItemGroupID.Add(Convert.ToInt32(item.ID));
                    else if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.Unit)
                        ListItemGroupID_TDV.Add(Convert.ToInt32(item.ID));
                    else if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.Saving)
                        ListItemGroupID_TKBD.Add(Convert.ToInt32(item.ID));
                    else if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.BusinessService)
                        ListItemGroupID_KD.Add(Convert.ToInt32(item.ID));
                }
            }

            ViewBag.ReportID = reportID;
            ViewBag.ListItemGroupID = ListItemGroupID;
            ViewBag.ListItemGroupID_TDV = ListItemGroupID_TDV;
            ViewBag.ListItemGroupID_TKBD = ListItemGroupID_TKBD;
            ViewBag.ListItemGroupID_KD = ListItemGroupID_KD;
            ViewBag.PoID = oEmployee.POID;
            return View(CD02Header);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Report02CDGetData(int reportID = 0, string reportDate = "", string isAgain = "N")
        {
            List<ItemGroupViewModel> listItemGroup = new List<ItemGroupViewModel>();
            List<int> ListItemGroupID = new List<int>();
            List<int> ListItemGroupID_TDV = new List<int>();
            List<int> ListItemGroupID_TKBD = new List<int>();
            List<int> ListItemGroupID_KD = new List<int>();
            CD02HeaderViewModel CD02Header = new CD02HeaderViewModel();
            CD02Header.ListDetail = new List<CD02DetailViewModel>();
            EmployeeViewModel oEmployee = (EmployeeViewModel)Session[Constant.EMP_SESSION];
            CD02Header.PoId = oEmployee.POID;
            CD02Header.ApprovedEmpId = oEmployee.ID;
            if (reportDate != "")
                CD02Header.ReportDate = reportDate;
            else
                CD02Header.ReportDate = DateTime.Now.Date.ToString("dd/MM/yyyy");
            int Total = 0;

            string Url = string.Format("api/Dictionary/ItemGroupGet/{0}?Code={1}&Name={2}&Status={3}&ReportId={6}&PageIndex={4}&PageSize={5}", 0, "", "", "", 0, Constant.PageSize, reportID);
            var rs = Helper.Invoke(Constant.Method.GET.ToString(), Url, null);

            if (rs.Code == "00")
            {
                int.TryParse(rs.Value.ToString(), out Total);
                dynamic oValue = rs.ListValue;
                foreach (var item in oValue)
                {
                    if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.Center)
                        ListItemGroupID.Add(Convert.ToInt32(item.ID));
                    else if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.Unit)
                        ListItemGroupID_TDV.Add(Convert.ToInt32(item.ID));
                    else if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.Saving)
                        ListItemGroupID_TKBD.Add(Convert.ToInt32(item.ID));
                    else if (Convert.ToInt32(item.CashFllowId) == (int)Constant.CashFllowType.BusinessService)
                        ListItemGroupID_KD.Add(Convert.ToInt32(item.ID));
                }
            }

            ViewBag.ReportID = reportID;
            ViewBag.ListItemGroupID = ListItemGroupID;
            ViewBag.ListItemGroupID_TDV = ListItemGroupID_TDV;
            ViewBag.ListItemGroupID_TKBD = ListItemGroupID_TKBD;
            ViewBag.ListItemGroupID_KD = ListItemGroupID_KD;
            ViewBag.isAgain = isAgain;
            ViewBag.PoID = oEmployee.POID;
            return PartialView(CD02Header);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult Report02CDGet(CD02HeaderViewModel CD02Header = null, int reportID = 0, int itemGroupId = 0, int cashFllowID = 0, string isAgain = "N")
        {
            var rs = Helper.Invoke("GET", string.Format("api/AccountingProvince/Report02CDSummary?id={0}&reportID={1}&itemGroupID={2}&reportDate={3}&cashFllowId={4}&poId={5}&isAgain={6}", new object[] { 0, reportID, itemGroupId, CD02Header.ReportDate, cashFllowID, CD02Header.PoId, isAgain }), null);
            if (rs != null && rs.Value != null)
            {
                dynamic oValue = rs.Value;
                if (oValue.ListDetail != null)
                {
                    CD02Header = CD02Header ?? new CD02HeaderViewModel();

                    foreach (dynamic dyn in oValue.ListDetail)
                    {
                        var oDetail = new CD02DetailViewModel()
                        {
                            Id = dyn.Id,
                            ItemId = dyn.ItemId,
                            ItemCode = dyn.ItemCode,
                            Formula = dyn.Formula,
                            DisplayName = dyn.DisplayName,
                            ParentId = dyn.ParentId,
                            IsVisible = dyn.IsVisible,
                            ItemGroupId = dyn.ItemGroupId,
                            FontBold = dyn.FontBold,
                            EditMode = dyn.EditMode,
                            AllowSummary = dyn.AllowSummary,
                            AllowVnd = dyn.AllowVnd,
                            AllowUsd = dyn.AllowUsd,
                            AmountVnd = dyn.AmountVnd,
                            AmountUsd = dyn.AmountUsd,
                            VisibleLevel = dyn.VisibleLevel
                        };

                        if (!CD02Header.ListDetail.Contains(oDetail))
                            CD02Header.ListDetail.Add(oDetail);
                    }
                }

            }

            ViewBag.reportID = reportID;
            ViewBag.itemGroupID = itemGroupId;
            ViewBag.cashFllowID = cashFllowID;
            return PartialView(CD02Header);
        }
        #endregion

        #region Report 03CD
        public ActionResult Report03CDReplace(int reportID = 0, int poId = 0, string reportDate = "")
        {
            try
            {
                EmployeeViewModel oEmployee = (EmployeeViewModel)Session[Constant.EMP_SESSION];
                var po = Repository.GetPOByID(poId);
               
                if (po != null && po.ParentID == oEmployee.POID)
                {
                    List<ItemGroupViewModel> listItemGroup = new List<ItemGroupViewModel>();
                    List<int> ListItemGroupID = new List<int>();
                    List<int> ListItemGroupID_TDV = new List<int>();
                    List<int> ListItemGroupID_TKBD = new List<int>();
                    List<int> ListItemGroupID_KD = new List<int>();
                   
                    CD03HeaderViewModel CD03Header = new CD03HeaderViewModel();
                    CD03Header.PoName = po.Name;
                    CD03Header.PoCode = po.Code;
                    CD03Header.PoId = po.ID;
                    CD03Header.IsApproved = true;

                    CD03Header.ListDetail = new List<CD03DetailViewModel>();

                    CD03Header.PoId = poId;
                    CD03Header.ApprovedEmpId = oEmployee.ID;
                    if (reportDate != "")
                        CD03Header.ReportDate = reportDate;
                    else
                        CD03Header.ReportDate = DateTime.Now.Date.ToString("dd/MM/yyyy");
                    int Total = 0;

                    string Url = string.Format("api/Dictionary/ItemGroupGet/{0}?Code={1}&Name={2}&Status={3}&ReportId={6}&PageIndex={4}&PageSize={5}", 0, "", "", "", 0, Constant.PageSize, reportID);
                    var rs = Helper.Invoke(Constant.Method.GET.ToString(), Url, null);

                    if (rs.Code == "00")
                    {

Cfm.Web.Mvc/Areas/CFMCounter/Views/Accounting/GetListMenuSummaryReport.cshtml
@model List<Cfm.Web.Mvc.Areas.Admin.Models.ReportListViewModel>
@{ Layout = null; }
@if (Model != null && Model.Count > 0)
{
    for (int i = 0; i < Model.Count; i++)
    {
        var item = Model[i];
        if (item.ReportType.Equals("04CD"))
        {
            <li>
                <a href="@Url.Action("Report04CD","Accounting",new { Area = "CFMCounter", @reportID = @item.Id})"><i class="fa fa-list-alt"></i><span>Tổng hợp 04-CĐ</span></a>
            </li>
            <li>
                <a href="@Url.Action("Report04CDManage","Accounting",new { Area = "CFMCounter", @reportID = @item.Id})"><i class="fa fa-list-alt"></i><span>Quản lý báo cáo 04-CĐ</span></a>
            </li>
            break;
        }

    }
}

Cfm.Web.Mvc/Areas/CFMCounter/Views/Accounting/Report04CDManage.cshtml
@model Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel.CD04HeaderViewModel
@{
    Layout = "~/Areas/CFMCounter/Views/Shared/_Layout.cshtml";
    int reportID = 0;
}
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    <li class="active">Quản lý báo cáo 04-CĐ</li>
</ol>

<div class="alert alert-info padding10">
    <div class="filter-bar">
        <div class="row ">
            <div class="filter-bar">
                <div class="row ">
                    <div class="col-sm-4 padding0">
                        <div class="date-picker-wrap padding0">
                            <div class="col-sm-5 p20">
                                <label>Từ ngày đến ngày</label>
                            </div>
                            <div class="col-sm-7 padding10">
                                <input class="form-control" name="from-date" id="txtDateRange" placeholder="Từ ngày - Đến ngày" type="text" readonly="readonly">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-4 padding0">
                        <div class="date-picker-wrap padding0">
                            <div class="col-sm-4 mt20">
                                <label>Trạng thái</label>
                            </div>
                            <div class="col-sm-6 mt10 padding0">
                                @Html.DropDownListFor(x => x.ReportStatus, (IEnumerable<SelectListItem>)ViewBag.ListReportStatus, new { @class = "form-control", @id = "cboReportStatus" })
                            </div>
                            <div class="col-sm-2 ">
                                <button id="search_key" onclick="ReportCD_Process.LoadReportManage(0,1)" name="search_key" class="btn btn-pns btn-cons  mt10" type="button"><i class="fa fa-fw fa-search"></i> Lọc dữ liệu</button>
                            </div>
                        </div>
                    </div>
                   
                </div>
            </div>

            @*<div class="col-md-4">
                    <button id="get_report_data" onclick="ReportCD_Process.GetReportData(@reportID,'N')" name="get_report_data" class="btn btn-pns btn-cons mt17 btn-sm" type="button"><i class="fa fa-fw fa-list-ul"></i> Hiển thị dữ liệu</button>
                    <button id="get_push_data" onclick="ReportCD_Process.GetReportData(@reportID,'Y')" name="get_push_data" class="btn btn-pns btn-cons mt17 btn-sm" type="button"><i class="fa fa-fw fa-arrow-down"></i> Lấy lại dữ liệu đẩy</button>
                </div>*@
            @*<div class="col-md-3">

                    <button id="search_key" onclick="" name="search_key" class="btn btn-pns btn-cons mt17 btn-sm" type="button"><i class="fa fa-fw fa-search"></i> Lấy lại dữ liệu đẩy</button>
                </div>*@
        </div>
    </div>
</div>
<div class="padding10 alert alert-info">
    <div class="container-fluid padding0">

        <div class="table-responsive" id="tblReport">
            @{ Html.RenderAction("Report04CDManageGet", "Accounting", new { @Area = "CFMCounter" }); }
        </div>
       
        @*<div class="container-fluid padding0">
                <button id="report04cdsummary" onclick="" name="search_key" class="btn btn-pns btn-cons btn-sm" type="button"><i class="fa fa-fw fa-book"></i> Xem 04-CĐ TH</button>
                <button id="report04cddetail" onclick="" name="search_key" class="btn btn-pns btn-cons btn-sm" type="button"><i class="fa fa-fw fa-book"></i> Xem 04-CĐ CT</button>

                <button id="report04cdupdate" onclick="common.Submitform('fUpdateReportCD')" name="search_key" class="btn btn-pns btn-cons btn-sm btn-dock-right" type="button"><i class="fa fa-fw fa-pencil"></i>  Sửa</button>
            </div>*@



    </div>
</div>

<script>
    filter.initDateRange(filterConfig.dateRange, null, null, 'right');
</script>

Cfm.Web.Mvc/Areas/CFMCounter/Views/Accounting/Report04CDManageGet.cshtml
@model List<Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel.CD04HeaderViewModel>
@using Cfm.Web.Mvc.Common;
@{
    int total = int.Parse(ViewBag.Total.ToString());
    int pageIndex = int.Parse(ViewBag.PageIndex.ToString());
    int pageSize = int.Parse(ViewBag.PageSize.ToString());
    int rPoID = ViewBag.PoID;
    //int refType = int.Parse(ViewBag.refType.ToString());
    int stt = (pageIndex - 1) * pageSize;


}

<table id="tblcontent" class="table table-striped table-bordered datatables dataTable no-footer table-fixed-header">
    <thead>
        <tr class="tr_head">
            <td class="w40 text-center">STT</td>
            <td class="w120 text-center">Ngày báo cáo</td>
            <td class="text-center">Trạng thái báo cáo</td>
            <td class="w250 text-center">Người xác nhận</td>
            <td class="w120 text-center">Ngày xác nhận</td>            
            <td class="w120 text-center"></td>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count > 0)
        {
            for (int i = 0; i < Model.Count; i++)
            {
                var item = Model[i];
                <tr>
                    <td>
                        @((stt + i + 1).ToString("N0"))
                    </td>
                    <td>
                        @item.ReportDate
                    </td>
                    <td>
                        @if (item.ReportStatus == "A")
                        {
                           <label class="label label-success">@item.ReportStatusName</label>
                        }
                        else if (item.ReportStatus == "L")
                        {
                            <label class="label label-warning">@item.ReportStatusName</label>
                        }
                        else
                        {
                            <label class="label label-danger">@item.ReportStatusName</label>
                        }

                    </td>
                    <td>
                        @item.ApprovedEmpName
                    </td>
                  
                    <td>
                        @item.ApprovedDate
                    </td>
                 
                    <td class="text-center padding1">
                        @if (item.ReportStatus == "L" || item.ReportStatus == "A")
                        {
                         
                            <div class="dropdown">
                                <button class="btn btn-default  dropdown-toggle" type="button" data-toggle="dropdown">
                                    <i class="fa fa-cog" aria-hidden="true"></i>...
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu dropdown-menu-right">
                                    <li><a title="Xem 04-CĐ TH"  onclick="Report_Process.View04CDTotal(@rPoID,'@item.ReportDate','@item.ReportDate',0,'CD04')"><i class="fa fa-book" aria-hidden="true"></i> Xem TH</a></li>
                                    <li><a title="Xem 04-CĐ CT"  onclick="Report_Process.ViewSummaryReport(@rPoID,'@item.ReportDate','@item.ReportDate',1,'CD04')"><i class="fa fa-book" aria-hidden="true"> Xem CT</i></a></li>
                                    @if (item.ReportStatus == "L")
                                    {
                                        <li><a title="Sửa" onclick="ReportCD_Process.ViewDetailReport(@item.Id)"><i class="fa fa-pencil" aria-hidden="true"></i> Sửa</a></li>
                                    }                                    
                                    
                                </ul>
                            </div>

                        }
                        
                    </td>
                </tr>

                <tr id="row-@item.Id" style="display:none; background-color:bisque">
                    <td colspan="9" id="col-@item.Id"></td>
                </tr>

            }
            <tr>
                <td colspan="9">
                    @Html.Raw(Utility.Page(total, pageIndex, 5, pageSize, (((pageIndex <= 0 ? 1 : pageIndex) - 1) * pageSize) + 1, pageSize * (pageIndex <= 0 ? 1 : pageIndex), "ReportCD_Process.LoadReportManage", "0"))
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td colspan="8">
                    <span>
                        Không tìm thấy dữ liệu...
                    </span>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    filter.initDateRange(filterConfig.dateRange, null, null, 'right');

</script>

Cfm.Web.Mvc/Areas/CFMCounter/Views/Accounting/Report04TQCreate.cshtml
@model Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel.TQ04HeaderViewModel

@using Cfm.Web.Mvc.Common;
@{ 
    int reportId = ViewBag.reportId;
}
<div class="panel panel-primary">
    <div class="panel-heading">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="fontbold color-white">
            Lập báo cáo 04-TQ
        </h4>
    </div>
    <div class="panel-body padding10">
        @using (Ajax.BeginForm("Report04TQUpdate", "Accounting", new { Area = "CFMCounter" }, new AjaxOptions { HttpMethod = Constant.Method.POST.ToString(), OnSuccess = "ReportTQ_Process.CreateReportSuccess(data," + reportId + ")" }, new { @id = "fCreateReportTQ" }))
        {
           
            @Html.HiddenFor(x => x.Id)
            @Html.HiddenFor(x => x.PoId)
            @Html.HiddenFor(x => x.DistrictPoId)
            @Html.HiddenFor(x => x.AmndEmpId)
            <div class="row">
                <div class="col-md-2 mt5">
                    <label for="ReportDate">Ngày báo cáo</label>
                   
                </div>
                <div class="col-md-3">
                   
                    @Html.TextBoxFor(x => x.ReportDate, new { @class = "form-control", @readonly = "readonly" })
                </div>
                <div class="col-md-3 mt5">
                    <button id="search_key" onclick="ReportTQ_Process.GetReportTQData(@reportId)" name="search_key" class="btn btn-pns btn-cons" style="margin-top:-5px !important;" type="button"><i class="fa fa-fw fa-search"></i> Kết xuất 04-TQ</button>
                </div>
            </div>

            <div class="row padding10">
                <div id="tblReportDetail">
                    @{ Html.RenderAction("Report04TQGet", "Accounting", new { @Area = "CFMCounter",@TQ04Header = Model, @reportId= reportId });}
                </div>               
            </div>

            <div class="modal-footer">
                <div class="row">
                    <div class="col-sm-12 text-right">
                        <button type="button" onclick="common.Submitform('fCreateReportTQ',false)" class="btn btn-pns text-right  btn-sm"><i class="glyphicon glyphicon-ok"></i> Cập nhật</button>
                        <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Thoát</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>


<script>
    $('#ReportDate').datepicker({
        format: 'dd/mm/yyyy', language: "vi", autoclose: true, endDate: new Date('@DateTime.Now.Year', '@(DateTime.Now.Month - 1)', '@DateTime.Now.Day', 0, 0, 0, 0)

    });

   
    common.Init();
</script>

Cfm.Web.Mvc/Areas/CFMCounter/Views/Accounting/Report04TQManage.cshtml
@model List<Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel.TQ04HeaderViewModel>

@{
    Layout = "~/Areas/CFMCounter/Views/Shared/_Layout.cshtml";    
    int reportId = ViewBag.reportId;
}
<script src="~/Scripts/CFM/Report04CDProcess.js"></script>
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "CFMCounter"})">Trang chủ</a></li>
    <li>Chức năng bưu cục</li>
    <li class="active">Quản trị 04-TQ</li>
</ol>

<div class="alert alert-info padding10">
    <div class="filter-bar">
        <div class="row ">
            <div class="filter-bar">
                <div class="row ">
                    <div class="col-sm-4 padding0">
                        <div class="date-picker-wrap padding0">
                            <div class="col-sm-5 p20">
                                <label>Từ ngày đến ngày</label>
                            </div>
                            <div class="col-sm-7 padding10">
                                <input class="form-control" name="from-date" id="txtDateRange" placeholder="Từ ngày - Đến ngày" type="text" readonly="readonly">
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <button id="search_key" onclick="ReportTQ_Process.LoadReportManage(0, 1, @reportId)" name="search_key" class="btn btn-pns btn-cons mt10" type="button"><i class="fa fa-fw fa-search"></i> Lọc dữ liệu</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="padding10 alert alert-info">
    <div class="container-fluid padding0">

        <div class="row">
            <div class="col-md-12 text-left">
                <a onclick="ReportTQ_Process.ViewCreateReport(0,'@reportId')" href="javascript:void(0)" class="btn btn-pns btn-sm padding5"><i class="fa fa-plus-square" aria-hidden="true"></i> Lập báo cáo</a>
            </div>
        </div>

        <div class="table-responsive" id="tblReport">
            @{ Html.RenderAction("Report04TQManageGet", "Accounting", new { @Area = "CFMCounter" ,@reportId = reportId}); }
        </div>      
    </div>
</div>

<script>
    filter.initDateRange(filterConfig.dateRange, null, null, 'right');
</script>

Cfm.Web.Mvc/Areas/CFMCounter/Views/Accounting/Report04TQManageGet.cshtml
@model List<Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel.TQ04HeaderViewModel>

@using Cfm.Web.Mvc.Common;
@{
    int total = int.Parse(ViewBag.Total.ToString());
    int pageIndex = int.Parse(ViewBag.PageIndex.ToString());
    int pageSize = int.Parse(ViewBag.PageSize.ToString());
    int rPoID = ViewBag.PoID;
    //int refType = int.Parse(ViewBag.refType.ToString());
    //int stt = (pageIndex - 1) * pageSize;
    int reportId = ViewBag.reportId;

}

<table id="tblcontent" class="table table-striped table-bordered datatables dataTable no-footer table-fixed-header">
    <thead>
        <tr class="tr_head">
            <td class="w40 text-center">STT</td>
            <td class="w250 text-center">Bưu cục lập</td>
            <td class="w250 text-center">Bưu cục Huyện</td>
            <td class="w120 text-center">Ngày lập</td>
            <td class="text-center">Người lập</td>
            <td class="w150 text-center"></td>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count > 0)
        {
            for (int i = 0; i < Model.Count; i++)
            {
                var item = Model[i];
                <tr>
                    <td>
                        @((i + 1).ToString("N0", new System.Globalization.CultureInfo("de-DE")))
                    </td>
                    <td>
                        @item.PoName
                    </td>
                    <td>
                        @item.DistrictPoName
                    </td>
                    <td>
                        @item.ReportDate
                    </td>

                    <td>
                        @item.AmndEmpName
                    </td>

                    <td class="text-center">
                        <a title="In nhu cầu" class="btn btn-success btn-xs" onclick="Report_Process.GetTQTotal(@rPoID, '@item.ReportDate','@item.ReportDate')"><i class="fa fa-book" aria-hidden="true"></i></a>                      
                        <a title="Sửa" class="btn btn-primary btn-xs" onclick="ReportTQ_Process.ViewCreateReport(@item.Id,@reportId)"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        <a title="Xóa" class="btn btn-danger btn-xs" onclick="ReportTQ_Process.DeleteReport(@item.Id,'@item.ReportDate',@reportId)"><i class="fa fa-trash" aria-hidden="true"></i></a>
                    </td>
                </tr>

                <tr id="row-@item.Id" style="display:none; background-color:bisque">
                    <td colspan="9" id="col-@item.Id"></td>
                </tr>

            }
            <tr>
                <td colspan="9">
                    @Html.Raw(Utility.Page(total, pageIndex, 5, pageSize, (((pageIndex <= 0 ? 1 : pageIndex) - 1) * pageSize) + 1, pageSize * (pageIndex <= 0 ? 1 : pageIndex), "ReportTQ_Process.LoadReportManage", "0"))
                </td>
            </tr>
        }
        else
        {
            <tr>
                <td colspan="8">
                    <span>
                        Không tìm thấy dữ liệu...
                    </span>
                </td>
            </tr>
        }
    </tbody>
</table>

<script>
    filter.initDateRange(filterConfig.dateRange, null, null, 'right');

</script>