Cfm.Web.Mvc/Areas/CFMCounter/Models/ViewModel/AccountingEntryViewModel.cs
using Cfm.Web.Mvc.Common;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel
{
    public class AccountingEntryViewModel
    {
        [Required(ErrorMessage="STT không được để trống!")]
        [Range(1,int.MaxValue,ErrorMessage="STT không hợp lệ!")]
        public int STT { get; set; }
        public string OrdinalNumberString { get; set; }
        public int OrdinalNumber { get; set; }
        public int Id { get; set; }
        public string TransNumber{ get; set; }
        public int AmndEmpId { get; set; }
        public int PoId { get; set; }
        public string PoCode { get; set; }
        public string PoName { get; set; }
        public int CreatedPoId { get; set; }
        public string CreatedPoCode { get; set; }
        public string CreatedPoName { get; set; }
        public int SendPoId { get; set; }
        public string SendPoCode { get; set; }
        public string SendPoName { get; set; }
        public int ReceivePoId { get; set; }
        public string ReceivePoCode { get; set; }
        public string ReceivePoName { get; set; }
        public int RefType { get; set; }
        public string TransDate { get; set; }
        public string RefTransNumber { get; set; }
        public decimal AmountVnd { get; set; }
        public decimal AmountUsd { get; set; }

        [Required(ErrorMessage = "Số tiền không được để trống!")]
        [MinLength(10,ErrorMessage="Độ dài không chính xác!")]
        public string Amount { get; set; }
        public int BudgetTypeId { get; set; }
        public int CashFllowId { get; set; }
        public string Description { get; set; }
        public string CurrencyType { get; set; }
        public string BudgetTypeName { get; set; }
        public string AmountInWord { get; set; }
        public bool Selected { get; set; }
        public decimal PaymentAmountVnd { get; set; }
        public decimal PaymentAmountUsd { get; set; }
        public int PoIdTemp1 { get; set; }
        public int PoIdTemp2 { get; set; }
        public decimal AmountUnitVnd { get; set; }
        public decimal AmountUnitUsd { get; set; }

        [Required(ErrorMessage="Số tiền không được để trống!")]
        [MinLength(10, ErrorMessage = "Độ dài không chính xác!")]
        public string AmountUnitString { get; set; }
        public string CurrencyTypeUnit { get; set; }
        public decimal AmountSavingVnd { get; set; }
        public decimal AmountSavingUsd { get; set; }

        [Required(ErrorMessage = "Số tiền không được để trống!")]
        [CustomMoneyValidation]
        public string AmountSavingString { get; set; }
        public string CurrencyTypeSaving { get; set; }
        public decimal AmountBSVnd { get; set; }
        public decimal AmountBSUsd { get; set; }

        [Required(ErrorMessage = "Số tiền không được để trống!")]
        [CustomMoneyValidation]
        public string AmountBSString { get; set; }
        public string CurrencyTypeBS { get; set; }
        public bool IsLvp { get; set; }
        public string BorrowMethod { get; set; }
        public string BorrowMethodUnit { get; set; }
        public string BorrowMethodSaving { get; set; }
        public string BorrowMethodBS { get; set; }
    }
}

Cfm.Web.Mvc/Areas/CFMDistrict/Controllers/AccountingEntryController.cs
using Cfm.Web.Mvc.Areas.Admin.Controllers;
using Cfm.Web.Mvc.Areas.Admin.Models;
using Cfm.Web.Mvc.Areas.CFMCounter.Models.ViewModel;
using Cfm.Web.Mvc.Areas.CFMDistrict.Models.ViewModels;
using Cfm.Web.Mvc.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cfm.Web.Mvc.Areas.CFMDistrict.Controllers
{
    [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.District })]
    public class AccountingEntryController : BaseController
    {
        // GET: CFMDistrict/AccountingEntry
        public ActionResult Index()
        {
            return View();
        }

        #region Tiếp nộp quỹ AllocateFund
        [AcceptVerbs(HttpVerbs.Get)]
        [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.District, (int)Constant.POLevel.Branch })]
        [AuthoritiesFunc(FunctionRole = new int[] { (int)Constant.Function.AccountingEntry_District_AllocateFundManage, (int)Constant.Function.FuntionBranch_AllocateFundManage })]
        public ActionResult AllocateFundManage()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.District, (int)Constant.POLevel.Branch })]
        public ActionResult AllocateFundGet(int id = 0, int poId = 0, string dateRange = "", int budgetTypeId = 0, int cashFllowId = 0, int refType = 0, int PageIndex = 1)
        {
            string fromDate = "";
            string toDate = "";
            if (dateRange != string.Empty)
            {
                fromDate = dateRange.Split('-')[0].Trim();
                toDate = dateRange.Split('-')[1].Trim();
            }
            else
            {
                fromDate = Session[Constant.TIMEWORK_SESSION].ToString();
                toDate = Session[Constant.TIMEWORK_SESSION].ToString();
            }
            List<AccountingEntryViewModel> ListAccountingEntry = new List<AccountingEntryViewModel>();
            EmployeeViewModel oEmployee = (EmployeeViewModel)Session[Constant.EMP_SESSION];
            var rs = Helper.Invoke(Constant.Method.GET.ToString(), string.Format("api/AccountingEntry/SearchAccountingEntry?id={0}&poId={1}&fromDate={2}&toDate={3}&budgetTypeId={4}&cashFllowId={5}&refTypeId={6}&PageIndex={7}&PageSize={8}", new object[] { 0, oEmployee.POID, fromDate, toDate, budgetTypeId, cashFllowId, refType, PageIndex, Common.Constant.PageSize }), null);
            if (rs != null && rs.ListValue != null)
            {
                foreach (dynamic dyn in rs.ListValue)
                {
                    var oEntry = new AccountingEntryViewModel();

                    oEntry.Id = int.Parse("0" + dyn.Id.ToString());
                    oEntry.TransNumber = dyn.TransNumber;
                    oEntry.AmndEmpId = int.Parse("0" + dyn.AmndEmpId.ToString());
                    oEntry.PoId = int.Parse("0" + dyn.PoId.ToString());
                    oEntry.PoCode = dyn.PoCode;

                    oEntry.SendPoId = int.Parse("0" + dyn.SendPoId.ToString());
                    oEntry.SendPoCode = dyn.SendPoCode;
                    oEntry.SendPoName = dyn.SendPoCode + " - " + dyn.SendPoName;

                    oEntry.ReceivePoId = int.Parse("0" + dyn.ReceivePoId.ToString());
                    oEntry.ReceivePoCode = dyn.ReceivePoCode;
                    oEntry.ReceivePoName = dyn.ReceivePoCode + " - " + dyn.ReceivePoName;

                    oEntry.RefType = int.Parse("0" + dyn.RefType.ToString());
                    oEntry.TransDate = dyn.TransDate;
                    oEntry.RefTransNumber = dyn.RefTransNumber;
                    oEntry.AmountVnd = Convert.ToDecimal(dyn.AmountVnd);
                    oEntry.AmountUsd = Convert.ToDecimal(dyn.AmountUsd);
                    oEntry.BudgetTypeId = int.Parse("0" + dyn.BudgetTypeId.ToString());
                    oEntry.CashFllowId = int.Parse("0" + dyn.CashFllowId.ToString());
                    oEntry.Description = dyn.Description;
                    oEntry.CurrencyType = dyn.CurrencyType;
                    oEntry.AmountUnitVnd = Convert.ToDecimal(dyn.AmountUnitVnd);
                    oEntry.AmountUnitUsd = Convert.ToDecimal(dyn.AmountUnitUsd);
                    oEntry.CurrencyTypeUnit = dyn.CurrencyTypeUnit;
                    oEntry.AmountSavingVnd = Convert.ToDecimal(dyn.AmountSavingVnd);
                    oEntry.AmountSavingUsd = Convert.ToDecimal(dyn.AmountSavingUsd);
                    oEntry.CurrencyTypeSaving = dyn.CurrencyTypeSaving;
                    oEntry.AmountBSVnd = Convert.ToDecimal(dyn.AmountBSVnd);
                    oEntry.AmountBSUsd = Convert.ToDecimal(dyn.AmountBSUsd);
                    oEntry.CurrencyTypeBS = dyn.CurrencyTypeBS;
                    oEntry.CreatedPoCode = dyn.CreatedPoCode;
                    if (!ListAccountingEntry.Contains(oEntry))
                        ListAccountingEntry.Add(oEntry);
                }

            }

            ViewBag.RefType = refType;

            return PartialView(ListAccountingEntry);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.District, (int)Constant.POLevel.Branch })]
        public ActionResult AllocateFundDetail(int Id, int refType)
        {
            AccountingEntryViewModel oAccountingEntry = new AccountingEntryViewModel();
            List<SelectListItem> ListPo = new List<SelectListItem>();
            List<SelectListItem> ListBudgetType = new List<SelectListItem>();
            List<SelectListItem> ListCashFlow = new List<SelectListItem>();
            List<SelectListItem> ListCurrencyType = new List<SelectListItem>();
            List<SelectListItem> ListBorrowMethod = new List<SelectListItem>();
            EmployeeViewModel oEmployee = (EmployeeViewModel)Session[Constant.EMP_SESSION];

            var rs = Helper.Invoke(Constant.Method.GET.ToString(), string.Format("api/AccountingEntry/SearchAccountingEntry?id={0}&poId={1}&fromDate={2}&toDate={3}&budgetTypeId={4}&cashFllowId={5}&refTypeId={6}&PageIndex={7}&PageSize={8}", new object[] { Id, oEmployee.POID, "", "", 0, 0, refType, 1, 1 }), null);
            if (rs != null && rs.ListValue != null)
            {
                foreach (dynamic dyn in rs.ListValue)
                {
                    oAccountingEntry.Id = int.Parse("0" + dyn.Id.ToString());
                    oAccountingEntry.TransNumber = dyn.TransNumber;
                    oAccountingEntry.AmndEmpId = int.Parse("0" + dyn.AmndEmpId.ToString());
                    oAccountingEntry.PoId = int.Parse("0" + dyn.PoId.ToString());
                    oAccountingEntry.PoCode = dyn.PoCode;

                    if (refType == (int)Constant.AccountingRefType.FundsReceive)
                    {
                        if (dyn.IsLvp != null && Convert.ToBoolean(dyn.IsLvp.ToString()))
                        {
                            oAccountingEntry.SendPoId = int.Parse("0" + dyn.SendPoId.ToString());
                            oAccountingEntry.SendPoCode = dyn.SendPoCode;
                            oAccountingEntry.SendPoName = "Ngân hàng Liên Việt";
                            oAccountingEntry.PoIdTemp1 = int.Parse("0" + dyn.SendPoId.ToString());
                        }
                        else
                        {
                            oAccountingEntry.SendPoId = int.Parse("0" + dyn.SendPoId.ToString());
                            oAccountingEntry.SendPoCode = dyn.SendPoCode;
                            oAccountingEntry.SendPoName = dyn.SendPoCode + " - " + dyn.SendPoName;
                            oAccountingEntry.PoIdTemp1 = int.Parse("0" + dyn.SendPoId.ToString());
                        }
                    }
                    else
                    {
                        oAccountingEntry.SendPoId = int.Parse("0" + dyn.SendPoId.ToString());
                        oAccountingEntry.SendPoCode = dyn.SendPoCode;
                        oAccountingEntry.SendPoName = dyn.SendPoCode + " - " + dyn.SendPoName;
                        oAccountingEntry.PoIdTemp1 = int.Parse("0" + dyn.SendPoId.ToString());
                    }

                    if (refType == (int)Constant.AccountingRefType.FundsSend)
                    {
                        if (dyn.IsLvp != null && Convert.ToBoolean(dyn.IsLvp.ToString()))
                        {
                            oAccountingEntry.SendPoId = int.Parse("0" + dyn.ReceivePoId.ToString());
                            oAccountingEntry.SendPoCode = dyn.ReceivePoCode;
                            oAccountingEntry.SendPoName = "Ngân hàng Liên Việt";
                            oAccountingEntry.PoIdTemp1 = int.Parse("0" + dyn.ReceivePoId.ToString());
                        }
                        else
                        {
                            oAccountingEntry.ReceivePoId = int.Parse("0" + dyn.ReceivePoId.ToString());
                            oAccountingEntry.ReceivePoCode = dyn.ReceivePoCode;
                            oAccountingEntry.ReceivePoName = dyn.ReceivePoCode + " - " + dyn.ReceivePoName;
                            oAccountingEntry.PoIdTemp1 = int.Parse("0" + dyn.ReceivePoId.ToString());
                        }
                    }
                    else
                    {
                        oAccountingEntry.ReceivePoId = int.Parse("0" + dyn.ReceivePoId.ToString());
                        oAccountingEntry.ReceivePoCode = dyn.ReceivePoCode;
                        oAccountingEntry.ReceivePoName = dyn.ReceivePoCode + " - " + dyn.ReceivePoName;
                        oAccountingEntry.PoIdTemp1 = int.Parse("0" + dyn.ReceivePoId.ToString());
                    }

                    oAccountingEntry.RefType = int.Parse("0" + dyn.RefType.ToString());
                    oAccountingEntry.TransDate = dyn.TransDate;
                    oAccountingEntry.RefTransNumber = dyn.RefTransNumber;

Cfm.Web.Mvc/Areas/CFMDistrict/Views/AccountingEntry/AllocateFundManage.cshtml
@{
    ViewBag.Title = "ReceiveFundsManage";
  
        Layout = "~/Areas/CFMDistrict/Views/Shared/_Layout.cshtml";
    

}
@using Cfm.Web.Mvc.Common
@{
    Cfm.Web.Mvc.Areas.Admin.Models.PostOfficeViewModel oPo = new Cfm.Web.Mvc.Areas.Admin.Models.PostOfficeViewModel();

    if (Session[Constant.PO_SESSION] != null)
    {
        oPo = (Cfm.Web.Mvc.Areas.Admin.Models.PostOfficeViewModel)Session[Constant.PO_SESSION];
    }
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    @if (oPo.POLevel == (int)Constant.POLevel.Counter)
    {
        <li class="active">
            Chức năng bưu cục
        </li>
    }
    else if (oPo.POLevel == (int)Constant.POLevel.District)
    {
        <li class="active">
            Kế toán Bưu điện Huyện
        </li>
    }
    else if (oPo.POLevel == (int)Constant.POLevel.Center)
    {
        <li class="active">
            Kế toán Bưu điện Tỉnh
        </li>
    }
    <li class="active">Tiếp nộp quỹ</li>
</ol>

<div class="card">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#FundsReceive"><strong>NHẬN QUỸ &nbsp;&nbsp;</strong></a></li>
        <li><a data-toggle="tab" href="#FundsSend"><strong>&nbsp;&nbsp;TIẾP/NỘP QUỸ</strong></a></li>
    </ul>
    <div class="tab-content padding10">
        <div id="FundsReceive" class="tab-pane fade in active">
            <div class="panel-body panel-no-padding">
                <div class="row">
                    <div class="col-md-12">
                        <div class="container-fluid">
                            <div class="alert alert-info">
                                <div class="filter-bar" data-magellan-expedition="fixed">
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <div class="date-picker-wrap">
                                                <div class="form-group">
                                                    <label for="txtDateRangeOne">Từ ngày - Đến ngày</label>
                                                    <input class="form-control" name="from-date" id="txtDateRangeOne" placeholder="Từ ngày - Đến ngày" type="text" readonly="readonly">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <button id="search_key" onclick="Accounting.SearchAccounting('@((int)Constant.AccountingRefType.FundsReceive)',1,'txtDateRangeOne')" name="search_key" class="btn btn-pns btn-cons mt17" type="button"><i class="fa fa-fw fa-search"></i> Lọc dữ liệu</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-left">
                                <a onclick="Accounting.CreateAllocateFund('@((int)Constant.AccountingRefType.FundsReceive)')" class="btn btn-pns"><i class="fa fa-plus-square"></i> Thêm mới</a>
                            </div>
                        </div>
                        <div class="table-responsive" id="ListFunds_@((int)Constant.AccountingRefType.FundsReceive)">
                            @{ Html.RenderAction("AllocateFundGet", "AccountingEntry", new { @Area = "CFMDistrict", @refType = (int)Constant.AccountingRefType.FundsReceive });}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="FundsSend" class="tab-pane fade">
            <div class="panel-body panel-no-padding">
                <div class="row">
                    <div class="col-md-12">
                        <div class="container-fluid">
                            <div class="alert alert-info">
                                <div class="filter-bar" data-magellan-expedition="fixed">
                                    <div class="row">
                                        <div class="col-sm-3">
                                            <div class="date-picker-wrap">
                                                <div class="form-group">
                                                    <label for="txtDateRangeTwo">Từ ngày - Đến ngày</label>
                                                    <input class="form-control" name="from-date" id="txtDateRangeTwo" placeholder="Từ ngày - Đến ngày" type="text" readonly="readonly">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <button id="search_key" onclick="Accounting.SearchAccounting('@((int)Constant.AccountingRefType.FundsSend)',1,'txtDateRangeTwo')" name="search_key" class="btn btn-pns btn-cons mt17" type="button"><i class="fa fa-fw fa-search"></i> Lọc dữ liệu</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 text-left">
                                <a onclick="Accounting.CreateAllocateFund('@((int)Constant.AccountingRefType.FundsSend)')" class="btn btn-pns"><i class="fa fa-plus-square"></i> Thêm mới</a>
                            </div>
                        </div>
                        <div class="table-responsive" id="ListFunds_@((int)Constant.AccountingRefType.FundsSend)">
                            <table id="tblcontent" class="table table-striped table-bordered datatables dataTable no-footer table-fixed-header">
                                <thead>
                                    <tr class="tr_head">
                                        <td class="text-center w40">STT</td>
                                        <td class="text-left">Mã giao dịch</td>
                                        <td class="w180 text-center">Ngày chuyển</td>
                                        <td class="w180 text-center">Đơn vị nộp</td>
                                        <td class="w180 text-center">Đơn vị nhận</td>
                                        <td class="w80 text-center">Số tiền</td>
                                        <td class="w80 text-center">Đơn vị</td>
                                        <td class="w120 text-center">Mã dịch vụ</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td colspan="8">
                                            <span>Chọn điều kiện để tìm kiếm...</span>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<form id="ConfigForm">
    @Html.AntiForgeryToken()
</form>


<script>
    filter.initDateRange(filterConfig.dateRangeOne, null, null, 'right');
    filter.initDateRange(filterConfig.dateRangeTwo, null, null, 'right');
</script>

Cfm.Web.Mvc/Areas/CFMDistrict/Views/AccountingEntry/FundLimitsDetail.cshtml
@model Cfm.Web.Mvc.Areas.CFMDistrict.Models.ViewModels.FundLimitsViewModel
@using Cfm.Web.Mvc.Common

<div class="panel panel-primary">
    <div class="panel-heading">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="fontbold color-white">
            @*@("Hạn mức lưu quỹ [" + Model.PoCode + " - " + Model.PoName + "]" + " năm " + Model.Nam)*@
            @("Hạn mức lưu quỹ [" + Model.PoCode + " - " + Model.PoName + "]")
        </h4>
    </div>
    <div class="panel-body pa pb0 pt10">
        @using (Ajax.BeginForm("FundLimitsUpdate", "AccountingEntry", new { Area = "CFMDistrict" }, new AjaxOptions { HttpMethod = Constant.Method.POST.ToString(), OnSuccess = "FundLimits_Process.OnSuccess" }, new { @id = "fFundLimitsDetail" }))
        {
            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x=>x.PoId)
            @Html.HiddenFor(x=>x.Nam)
            @Html.HiddenFor(x=>x.Thang)
            @Html.HiddenFor(x=>x.PoCode)
            @Html.HiddenFor(x=>x.PoName)
            <div class="form-group">
                <h3 class="fontboldUper" style="color:#5f7676 !important;">
                    @("Đơn vị: " + Model.PoCode + " - " + Model.PoName)
                </h3>
            </div>
            @*<div class="form-group">
                <span class="fontboldUper">
                    @("Năm: " + Model.Nam)
                </span>
            </div>*@
            <hr />
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="ThuTBString">Thu Trung bình/Ngày</label>
                        @Html.TextBoxFor(x => x.ThuTBString, new { @class = "form-control NumberMask", @placeholder = "Thu Trung Bình/Ngày" })
                        @Html.ValidationMessageFor(x => x.ThuTBString)
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="ThuTBString">Chi Trung bình/Ngày</label>
                        @Html.TextBoxFor(x => x.ChiTBString, new { @class = "form-control NumberMask", @placeholder = "Chi Trung Bình/Ngày" })
                        @Html.ValidationMessageFor(x => x.ChiTBString)
                    </div>
                </div>
            </div>
           

            <div class="form-group">
                <label for="K1String">Hệ số K1</label>
                @Html.TextBoxFor(x => x.K1String, new { @class = "form-control NumberMask", @placeholder = "Hệ số K1" })
                @Html.ValidationMessageFor(x => x.K1String)
            </div>

            <div class="form-group">
                <label for="K2String">Hệ số K2</label>
                @Html.TextBoxFor(x => x.K2String, new { @class = "form-control NumberMask", @placeholder = "Hệ số K2" })
                @Html.ValidationMessageFor(x => x.K2String)
            </div>
            
            <div class="form-group">
                <label for="K3String">Hệ số K3</label>
                @Html.TextBoxFor(x => x.K3String, new { @class = "form-control NumberMask", @placeholder = "Hệ số K3" })
                @Html.ValidationMessageFor(x => x.K3String)
            </div>

            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="DinhMucDeXuatString">Hạn mức đề xuất</label>
                        @Html.TextBoxFor(x => x.DinhMucDeXuatString, new { @class = "form-control NumberMask", @placeholder = "Hạn mức đề xuất" })
                        @Html.ValidationMessageFor(x => x.DinhMucDeXuatString)
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="DinhMucDuocGiaoString">Hạn mức được giao</label>
                        @Html.TextBoxFor(x => x.DinhMucDuocGiaoString, new { @class = "form-control NumberMask", @placeholder = "Hạn mức được giao" })
                        @Html.ValidationMessageFor(x => x.DinhMucDuocGiaoString)
                    </div>
                </div>
            </div>

            <div class="modal-footer pb0">
                <div class="row">
                    <div class="col-sm-12 text-right">
                        <button type="button" onclick="common.Submitform('fFundLimitsDetail', true)" class="btn btn-pns text-right  btn-sm"><i class="glyphicon glyphicon-ok"></i> Cập nhật</button>
                        <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Thoát</button>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script>
    common.Init();
</script>

Cfm.Web.Mvc/Areas/CFMDistrict/Views/AccountingEntry/FundLimitsManage.cshtml
@using Cfm.Web.Mvc.Common
@{
    ViewBag.Title = "FundLimitsManage";
    Layout = "~/Areas/CFMDistrict/Views/Shared/_Layout.cshtml";
}
@{
    Cfm.Web.Mvc.Areas.Admin.Models.PostOfficeViewModel oPo = new Cfm.Web.Mvc.Areas.Admin.Models.PostOfficeViewModel();

    if (Session[Constant.PO_SESSION] != null)
    {
        oPo = (Cfm.Web.Mvc.Areas.Admin.Models.PostOfficeViewModel)Session[Constant.PO_SESSION];
    }
}
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>

    <li class="active">
        Nghiệp vụ hỗ trợ BĐH
    </li>

    <li class="active">Hạn mức lưu quỹ tiền mặt</li>
</ol>

@*<div class="row">
    <div class="col-md-12">
        <div class="container-fluid">
            <div class="alert alert-info">
                <div class="filter-bar" data-magellan-expedition="fixed">
                    <div class="row">
                        <div class="col-sm-3">
                            <div class="date-picker-wrap">
                                <div class="form-group">
                                    <label for="txtDateRangeOne">Năm</label>
                                    @Html.DropDownList("FundLimitsNam", (IEnumerable<SelectListItem>)ViewBag.ListNam, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <button id="search_key" name="search_key" onclick="FundLimits_Process.ListFundLimits()" class="btn btn-pns btn-cons mt17" type="button"><i class="fa fa-fw fa-search"></i> Lọc dữ liệu</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>*@

<div class="row">
    <div class="col-md-12">
        <div class="container-fluid">
            <div class="alert alert-info">
                <div class="filter-bar" data-magellan-expedition="fixed">
                    <div class="table-responsive" id="ListFundLimits">
                        @{ Html.RenderAction("FundLimitsGet", "AccountingEntry", new { @Area = "CFMDistrict" });}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>