Cfm.Web.Mvc/Areas/Admin/Controllers/ReportConfigurationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Cfm.Web.Mvc.Areas.Admin.Models;
using Cfm.Web.Mvc.Common;

namespace Cfm.Web.Mvc.Areas.Admin.Controllers
{
    [FilterRoleToAction(Role = new int[] { (int)Constant.POLevel.Center })]
    public class ReportConfigurationController : BaseController
    {
        // GET: Admin/ReportConfiguration
        public ActionResult Index()
        {
            return View();
        }

        #region Dampt Create

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfigReport(int ReportId = 0, string ReportType = "")
        {
            ViewBag.ReportId = ReportId;
            ViewBag.ReportType = ReportType;
            return View();
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfigTH(int ReportId = 0, string ReportType = "")
        {
            List<ItemGroupViewModel> ListItemGroup = new List<ItemGroupViewModel>();
            int Total = 0;

            try
            {
                string Url = string.Format("api/Dictionary/ItemGroupSearch/{0}?Code={1}&Name={2}&Status={3}&ReportId={4}&PageIndex={5}&PageSize={6}", 0, "", "", "", ReportId, 0, Constant.PageSize);
                var rs = Helper.Invoke(Constant.Method.GET.ToString(), Url, null);

                if (rs.Code == "00")
                {
                    int.TryParse(rs.Value.ToString(), out Total);
                    dynamic oValue = rs.ListValue;
                    foreach (var item in oValue)
                    {
                        ItemGroupViewModel oItemGroup = new ItemGroupViewModel();
                        oItemGroup.ID = Convert.ToInt32(item.ID);
                        oItemGroup.Code = (item.Code).ToString();
                        oItemGroup.Name = (item.Name).ToString();
                        oItemGroup.ReportId = Convert.ToInt32(item.ReportId);
                        oItemGroup.Status = (item.Status).ToString();
                        oItemGroup.VisibleIndex = Convert.ToInt32(item.VisibleIndex);
                        ListItemGroup.Add(oItemGroup);
                    }
                }
                else
                {
                    ListItemGroup = null;
                }
            }
            catch
            {
                ListItemGroup = null;
            }

            ViewBag.ReportType = ReportType;
            return PartialView(ListItemGroup);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfigTHCreate(int id = 0, int reportID = 0, int itemGroupID = 0, int parentId = 0, string reportType = "", int VisibleLevel = 1, int VisibleIndex = 1)
        {
            ReportConfigViewModel oReportConfigViewModel = new ReportConfigViewModel();


            List<SelectListItem> ListEditMode = new List<SelectListItem>();
            int Total = 0;
            #region ListEditMode Kiểu nhập liệu
            foreach (var item in Repository.ListItemEditMode)
            {
                ListEditMode.Add(new SelectListItem
                {
                    Text = item.Value,
                    Value = item.Key.ToString()
                });
            }
            #endregion

            if (id > 0)
            {
                var rs = Helper.Invoke("GET", string.Format("api/Configuration/GetReportConfig?id={0}&reportID ={1}&itemGroupID ={2}&isVisible={3}", new object[] { id, reportID, itemGroupID, string.Empty }), null);
                if (rs != null && rs.ListValue != null)
                {
                    dynamic dyn = rs.ListValue[0];
                    oReportConfigViewModel = new ReportConfigViewModel()
                    {
                        Id = dyn.Id,
                        ReportId = dyn.ReportId,
                        ItemId = dyn.ItemId,
                        ItemCode = dyn.ItemCode,
                        ItemName = dyn.ItemName,
                        DisplayName = dyn.DisplayName,
                        ParentId = dyn.ParentId,
                        VisibleLevel = dyn.VisibleLevel,
                        VisibleIndex = dyn.VisibleIndex,
                        IsVisible = dyn.IsVisible,
                        ItemGroupId = dyn.ItemGroupId,
                        IsEmpty = dyn.IsEmpty,
                        FontBold = dyn.FontBold,
                        EditMode = dyn.EditMode,
                        AllowSummary = dyn.AllowSummary,
                        AllowVnd = dyn.AllowVnd,
                        AllowUsd = dyn.AllowUsd,
                        AllowAccumulate = dyn.AllowAccumulate,
                        AccumulateUsd = dyn.AccumulateUsd,
                        AllowShowReport = dyn.AllowShowReport,
                        AllowSummaryBottom = dyn.AllowSummaryBottom
                    };
                }

            }
            else
            {
                oReportConfigViewModel = new ReportConfigViewModel();

                oReportConfigViewModel.ReportId = reportID;
                oReportConfigViewModel.ItemGroupId = itemGroupID;
                oReportConfigViewModel.ParentId = parentId;
                oReportConfigViewModel.VisibleIndex = VisibleIndex;
                oReportConfigViewModel.VisibleLevel = VisibleLevel;
            }

            #region Danh sách Dịch vụ
            try
            {
                string Url = string.Format("api/Dictionary/ItemListSearch/{0}?Code={1}&Name={2}&IsReceiptItem={3}&MoneyType={4}&ItemTypeId={5}&IsSummary={6}&ParentId={7}&PartnerId={8}&BudgetTypeId={9}&BorrowTypeId={10}&CashFlowID={11}&PageIndex={12}&PageSize={13}",
                    0, "", "", "", 0, 0, "", 0, 0, 0, 0, 0, 1, Constant.PageSize);
                var rs = Helper.Invoke(Constant.Method.GET.ToString(), Url, null);

                if (rs.Code == "00")
                {
                    oReportConfigViewModel.ListItem = new List<ItemListViewModel>();
                    int.TryParse(rs.Value.ToString(), out Total);
                    dynamic oValue = rs.ListValue;
                    foreach (var item in oValue)
                    {
                        ItemListViewModel oItem = new ItemListViewModel();
                        oItem.Id = int.Parse("0" + (item.Id ?? "0").ToString());
                        oItem.Code = (item.Code ?? "").ToString();
                        oItem.Name = (item.Name ?? "").ToString();
                        oItem.IsReceiptItem = (item.IsReceiptItem ?? "").ToString();
                        oItem.MoneyType = int.Parse("0" + (item.MoneyType ?? "0").ToString());
                        oItem.ItemTypeId = int.Parse("0" + (item.ItemTypeId ?? "0").ToString());
                        oItem.IsSummary = (item.IsSummary ?? "N").ToString();
                        oItem.bIsSummary = (oItem.IsSummary == "" || oItem.IsSummary == "N" ? false : true);
                        oItem.Formula = (item.Formula ?? "").ToString();
                        oItem.ParentId = int.Parse("0" + (item.ParentId ?? "0").ToString());
                        oItem.PartnerId = int.Parse("0" + (item.PartnerId ?? "0").ToString());
                        oItem.BudgetTypeId = int.Parse("0" + (item.BudgetTypeId ?? "0").ToString());
                        oItem.BorrowTypeId = int.Parse("0" + (item.BorrowTypeId ?? "0").ToString());
                        oItem.CashFlowId = int.Parse("0" + (item.CashFlowId ?? "0").ToString());
                        oItem.Description = (item.Description ?? "").ToString();
                        oReportConfigViewModel.ListItem.Add(oItem);
                    }
                }
                else
                {
                    oReportConfigViewModel.ListItem = null;
                }
            }
            catch
            {
                oReportConfigViewModel.ListItem = null;
            }
            #endregion


            ViewBag.PageIndex = 1;
            ViewBag.PageSize = Constant.PageSize;
            ViewBag.ToTal = Total;
            ViewBag.ListEditMode = ListEditMode;
            ViewBag.ReportType = reportType;
            return PartialView(oReportConfigViewModel);
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult ConfigTHGet(int reportID = 0, int itemGroupId = 0, string reportType = "")
        {
            List<ReportConfigViewModel> ListReportConfig = new List<ReportConfigViewModel>();
            int Total = 0;

            try
            {
                string Url = string.Format("api/Configuration/GetReportConfig?id={0}&reportID={1}&itemGroupID={2}&isVisible={3}", 0, reportID, itemGroupId, "");
                var rs = Helper.Invoke(Constant.Method.GET.ToString(), Url, null);

                if (rs.Code == "00")
                {
                    int.TryParse((rs.Value ?? "").ToString(), out Total);
                    dynamic oValue = rs.ListValue;
                    foreach (var item in oValue)
                    {
                        ReportConfigViewModel oItemReportConfig = new ReportConfigViewModel();
                        oItemReportConfig.Id = Convert.ToInt32("0" + (item.Id ?? "0").ToString());
                        oItemReportConfig.ReportId = int.Parse("0" + (item.ReportId ?? "0").ToString());
                        oItemReportConfig.ItemId = int.Parse("0" + (item.ItemId ?? "0").ToString());
                        oItemReportConfig.ItemCode = (item.ItemCode ?? "0").ToString();
                        oItemReportConfig.ItemName = (item.ItemName ?? "").ToString();
                        oItemReportConfig.DisplayName = (item.DisplayName ?? "").ToString();
                        oItemReportConfig.ParentId = int.Parse("0" + (item.ParentId ?? "0").ToString());
                        oItemReportConfig.VisibleLevel = int.Parse("0" + (item.VisibleLevel ?? "0").ToString());
                        oItemReportConfig.VisibleIndex = int.Parse("0" + (item.VisibleIndex ?? "0").ToString());

Cfm.Web.Mvc/Areas/Admin/Views/ReportConfiguration/ConfigCDCreate.cshtml
@using Cfm.Web.Mvc.Common;
@model Cfm.Web.Mvc.Areas.Admin.Models.ReportConfigViewModel
@{
    int total = int.Parse(ViewBag.Total.ToString());
    int pageIndex = int.Parse(ViewBag.PageIndex.ToString());
    int pageSize = int.Parse(ViewBag.PageSize.ToString());

    int stt = (pageIndex - 1) * pageSize;
    string refType = ((int)Constant.RefType.ItemList).ToString().PadLeft(3, '0');

}
<div class="panel panel-primary">
    <div class="panel-heading">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4>
            Thêm mới chỉ tiêu
        </h4>
    </div>
    <div class="panel-body">

        @using (Ajax.BeginForm("ConfigCDUpdate", "ReportConfiguration", new { Area = "Admin" }, new AjaxOptions { HttpMethod = "Post", OnSuccess = "Config_Process.ConfigSuccess(data,'04CD'," + Model.ReportId + "," + Model.ItemGroupId + ")" }, new { @id = "fReportConfigCreate" }))
        {
            @Html.HiddenFor(model => model.Id)
            @Html.HiddenFor(model => model.ReportId)
            @Html.HiddenFor(model => model.ItemGroupId)
            @Html.HiddenFor(model => model.ParentId)
            @Html.HiddenFor(model => model.ItemId)
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.DisplayName, htmlAttributes: new {})
                        @Html.EditorFor(model => model.DisplayName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DisplayName)
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.VisibleLevel, htmlAttributes: new { })
                                @Html.EditorFor(model => model.VisibleLevel, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.VisibleLevel)
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                @Html.LabelFor(model => model.VisibleIndex, htmlAttributes: new {  })
                                @Html.EditorFor(model => model.VisibleIndex, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.VisibleIndex)
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="checkbox-inline">@Html.CheckBoxFor(model => model.IsEmpty, new { @id = "chkIsEmpty" }) Chỉ tiêu trắng</label>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.EditMode, htmlAttributes: new { })
                        @Html.DropDownListFor(model => model.EditMode, (IEnumerable<SelectListItem>)ViewBag.ListItemEditMode, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EditMode)
                    </div>

                    <div class="form-group">
                        <label class="checkbox-inline">@Html.CheckBoxFor(model => model.AllowVnd) Tiền VNĐ</label>
                    </div>

                    <div class="form-group">
                        <label class="checkbox-inline">@Html.CheckBoxFor(model => model.AllowUsd) Tiền USD</label>
                    </div>

                    <div class="form-group">
                        <label class="checkbox-inline">@Html.CheckBoxFor(model => model.FontBold) Chữ đậm</label>
                    </div>

                    <div class="form-group">
                        <label class="checkbox-inline">@Html.CheckBoxFor(model => model.AllowSummary) Cộng lên chỉ tiêu tổng hợp</label>
                    </div>

                    <div class="form-group">
                        <label class="checkbox-inline">@Html.CheckBoxFor(model => model.AllowShowReport) Hiển thị lên báo cáo</label>
                    </div>

                    <div class="form-group">
                        <label class="checkbox-inline">@Html.CheckBoxFor(model => model.DisableFormula) Vô hiệu hóa công thức</label>
                    </div>
                </div>

                <div class="col-md-8">
                    <div class="filter-bar">
                        <div class="form-group">
                            <label>Thông tin tìm kiếm</label>
                            <div class="input-group">
                                <input class="form-control text-uppercase" id="txtSearchContent" placeholder="Mã chỉ tiêu, tên chỉ tiêu" type="text">
                                <span class="input-group-btn">
                                    <button id="search_item" onclick="Dic.GetItemForConfig(@refType,1)" name="search_item" class="btn btn-pns btn-cons" type="button"><i class="fa fa-fw fa-search"></i> Tìm kiếm</button>
                                </span>
                            </div>

                        </div>
                    </div>
                    <div id="ListDic">
                        @*@{ Html.RenderAction("ItemListGet", "Dictionary", new { @Area = "Admin", @forConfig = 1 });}*@


                        <div class="table-responsive maxheight450">
                            <table id="tblListItem" class="table table-striped table-bordered datatables dataTable no-footer">
                                <thead>
                                    <tr class="tr_head">
                                        <td class="w40 text-center"></td>
                                        <td class="w80 text-center">ID</td>
                                        <td class="w180 text-center">Mã Chỉ tiêu</td>
                                        <td class="text-left">Tên Chỉ tiêu</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null && Model.ListItem.Count > 0)
                                    {
                                        for (int i = 0; i < Model.ListItem.Count; i++)
                                        {
                                            //var item = Model.ListItem[i];

                                            <tr>
                                                @Html.HiddenFor(x => Model.ListItem[i].Id)
                                                <td class="text-center">
                                                    @Html.CheckBoxFor(x => Model.ListItem[i].Selected)
                                                </td>
                                                <td class="text-left">
                                                    @Model.ListItem[i].Id
                                                </td>
                                                <td class="text-left">
                                                    @Model.ListItem[i].Code
                                                </td>
                                                <td class="text-left">
                                                    <span>@Model.ListItem[i].Name</span>
                                                </td>
                                            </tr>
                                        }
                                        <tr>
                                            <td colspan="4">
                                                @Html.Raw(Utility.Page(total, pageIndex, 3, pageSize, (((pageIndex <= 0 ? 1 : pageIndex) - 1) * pageSize) + 1, pageSize * (pageIndex <= 0 ? 1 : pageIndex), "Dic.GetItemForConfig", refType, false))
                                            </td>
                                        </tr>
                                    }
                                    else
                                    {
                                        <tr>
                                            <td colspan="3">
                                                <span>
                                                    Không tìm thấy dữ liệu...!
                                                </span>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>

            </div>

            @Html.ValidationSummary(true)
            @Html.AntiForgeryToken()

            <div class="modal-footer">
                <div class="row">
                    <button type="button" onclick="Config_Process.GetSelectedItem()" class="btn btn-pns btn-sm"><i class="fa fa-check"></i> Cập nhật</button>
                    <button type="button" class="btn btn-danger btn-sm" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> Thoát</button>
                </div>
            </div>

        }
    </div>
</div>


<script>
    $("#tblListItem input[type=checkbox]").change(function () {
        $("#tblListItem input[type=checkbox]").prop('checked', false);
        $(this).prop('checked', true);
    });
</script>

Cfm.Web.Mvc/Areas/Admin/Views/ReportConfiguration/ConfigReport.cshtml
@{
    ViewBag.Title = "ConfigReport";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

@{ 
    int ReportId = int.Parse(ViewBag.ReportId.ToString());
    string ReportType = ViewBag.ReportType.ToString();
}

@{Html.RenderAction("ConfigTH", "ReportConfiguration", new { @Area = "Admin", @ReportId = ReportId });}

Cfm.Web.Mvc/Areas/Admin/Views/ReportConfiguration/ConfigReportGet.cshtml
@model List<Cfm.Web.Mvc.Areas.Admin.Models.ReportConfigViewModel>


<table id="tblcontent" class="table table-striped table-bordered datatables dataTable no-footer table-fixed">
    <thead>
        <tr class="tr_head">
            <th class="w40 text-center">#</th>
            <th class="w80 text-center">Chỉ tiêu</th>
            <th class="text-left">Mã Chỉ tiêu TM</th>
            <th class="w80 text-center">Chỉ tiêu USD</th>
            <th class="w80 text-center">Mã chỉ tiêu lũy kế</th>
            <th class="w80 text-center">Chỉ tiêu USD lũy kế</th>
            <td class="w80"><a href="javascript:void(0)" class="btn btn-primary btn-sm"></a></td>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Count > 0)
        {
            for (int j = 0; j < 20; j++)
            {
                var item = Model[j];
                <tr>
                    <td>@((j + 1).ToString("N0"))</td>
                    <td>@item.DisplayName</td>
                    <td>@item.ItemId</td>
                    <td>@Html.CheckBoxFor(x => item.AllowUsd)</td>
                    <td>@Html.CheckBoxFor(x => item.AllowAccumulate)</td>
                    <td>@Html.CheckBoxFor(x => item.AccumulateUsd)</td>
                    <td></td>
                </tr>
            }
        }
    </tbody>
</table>

Cfm.Web.Mvc/Areas/Admin/Views/ReportConfiguration/ConfigTH.cshtml
@using Cfm.Web.Mvc.Common;
@model List<Cfm.Web.Mvc.Areas.Admin.Models.ItemGroupViewModel>

@{
    string ReportType = ViewBag.ReportType.ToString();
}

<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    <li class="active">Cấu hình Báo cáo</li>
</ol>



@if (Model != null && Model.Count > 0)
{
    int Total = Model.Count;
    if (Model.Count > 2)
    {
        Total = Model.Count - 2;
    }

    if (ReportType == "02TH" || ReportType == "03TH") //LOAD LOẠI BÁO CÁO 02TH và 03TH
    {
        for (int i = 0; i < Total; i++)
        {
            var item = Model[i];
            var Part = "Part" + item.ID;

            <div class="panel padding1">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#panel-@item.ID" data-toggle="collapse">
                            <strong> @("Phần " + Utility.IntToRoman(i + 1) + ": " + item.Name)</strong>
                        </a>
                    </h4>
                </div>
                <div id="panel-@item.ID" class="panel-collapse in">
                    <div class="panel-body panel-no-padding padding0">
                        <div class="table-responsive h350 scroll" id="@Part">
                            @{ Html.RenderAction("ConfigTHGet", "ReportConfiguration", new { @reportID = item.ReportId, @itemGroupId = item.ID, @Area = "Admin" });}
                        </div>
                    </div>
                </div>
            </div>
        }

        if (Total != Model.Count)
        {
            <div class="row">
                @for (int j = 1; j <= 2; j++)
                {
                    var item = Model[Model.Count - j];
                    <div class="col-sm-6">
                        <div class="panel padding1">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a href="#panel-@item.ID" data-toggle="collapse">
                                        @(j == 1 ? "Tài sản" : "Nguồn vốn")
                                    </a>
                                </h4>
                            </div>
                            <div id="panel-@item.ID" class="panel-collapse in">
                                <div class="panel-body panel-no-padding padding0">
                                    <div class="table-responsive h350 scroll">
                                        @{ Html.RenderAction("ConfigTHGet", "ReportConfiguration", new { @reportID = item.ReportId, @itemGroupId = item.ID, @Area = "Admin" });}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                }
            </div>
        }
    }
    else if (ReportType == "01TH")//LOAD LOẠI BÁO CÁO 01TH
    {
        <div class="panel padding1">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a href="#panelOne" data-toggle="collapse">
                        <strong> PHẦN I: CÂN ĐỐI TẠI BAN TÀI CHÍNH KẾ TOÁN</strong>
                    </a>
                </h4>
            </div>
            <div id="panelOne" class="panel-collapse in">
                <div class="panel-body padding0">
                    <div class="row">
                        @for (int i = 0; i < Model.Take(2).Count(); i++)
                        {
                            var item = Model[i];
                            var Part = "Part" + item.ID;
                            <div class="col-md-6">
                                <div class="table-responsive h350 scroll" id="@Part">
                                    @{ Html.RenderAction("ConfigTHGet", "ReportConfiguration", new { @reportID = item.ReportId, @itemGroupId = item.ID, @Area = "Admin" });}
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>

    <div class="panel padding1">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a href="#panelTwo" data-toggle="collapse">
                    <strong> PHẦN II: CÂN ĐỐI TOÀN TỔNG CÔNG TY</strong>
                </a>
            </h4>
        </div>
        <div id="panelTwo" class="panel-collapse in">
            <div class="panel-body padding0">
                <div class="row">
                    @for (int i = Model.Take(2).Count(); i < Model.Count(); i++)
                    {
                        var item = Model[i];
                        var Part = "Part" + item.ID;
                        <div class="col-md-6">
                            <div class="table-responsive h350 scroll" id="@Part">
                                @{ Html.RenderAction("ConfigTHGet", "ReportConfiguration", new { @reportID = item.ReportId, @itemGroupId = item.ID, @Area = "Admin" });}
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    }
}
else
{
    <span>
        Không tìm thấy Nhóm Chỉ tiêu.
    </span>
}
<br />

Cfm.Web.Mvc/Areas/Admin/Views/ReportConfiguration/ConfigTQ.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    int reportID = ViewBag.ReportID;
    List<int> ListItemGroupID = ViewBag.ListItemGroupID;
}
<ol class="breadcrumb">
    <li><a href="@Url.Action("Index","Home", new{Area = "Admin"})">Trang chủ</a></li>
    <li class="active">@ViewBag.PageHeader</li>
</ol>
<div class="panel panel-default">
    @if (ListItemGroupID.Count > 0)
    {
        <div class="panel-heading">
            <h4 class="panel-title">
                <a href="#panelCash" data-toggle="collapse">
                    <strong> DANH SÁCH DỊCH VỤ BÁO CÁO</strong>
                </a>
            </h4>
        </div>
        <div id="panelCash" class="panel-collapse in">
            <div class="panel-body">
                <div class="row">
                    <div id="@( "Part" + ListItemGroupID[0].ToString())" class="col-md-12">
                        @{ Html.RenderAction("ConfigTQGet", "ReportConfiguration", new { area = "Admin", @reportID = reportID, @itemGroupId = ListItemGroupID[0] });}
                    </div>
                </div>
            </div>
        </div>
                            }
</div>

Cfm.Web.Mvc/Areas/Admin/Views/ReportConfiguration/Report02_03_TH.cshtml
@using Cfm.Web.Mvc.Common;
@model List<Cfm.Web.Mvc.Areas.Admin.Models.ItemGroupViewModel>

@if(Model != null && Model.Count > 0)
{
    for(int i =0; i< Model.Count; i++)
    {
        var item = Model[i];
        <h2 class="cRed">@("Phần " + Utility.IntToRoman(i + 1) + ": " + item.Name)</h2>
        <div class="table-responsive h350">
            @{ Html.RenderAction("ConfigReportGet", "ReportConfiguration", new { @reportID = item.ReportId, @itemGroupId = item.ID, @Area = "Admin" });}
        </div>
    }
}
else
{
    <span>
        Không tìm thấy Nhóm Chỉ tiêu.
    </span>
}

<div class="row">
    <div class="col-sm-6">
        <span><h2 class="cRed">Tài sản</h2></span>
    </div>
    <div class="col-sm-6">
        <span><h2 class="cRed">Nguồn vốn</h2></span>
    </div>
</div>